// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgncmoejqngxjcqvxjgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbmNtb2VqcW5neGpjcXZ4amdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTg5MDksImV4cCI6MjA2MTIzNDkwOX0.m9eYLCRkZZWdtbg1dGepILyP1Ag78kPadaHiVlvA4FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);